security:
  oauth2:
    client:
      clientId: client id
      clientSecret: secret
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
  user:
    name: user
    password: pwd

#Spring-data-rest
spring:
  data:
    rest:
      return-body-on-create: true

